# Generated by Django 4.2.2 on 2023-06-23 19:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('youtube_link', models.URLField()),
                ('video_name', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(upload_to='')),
            ],
        ),
    ]
