# Generated by Django 4.2.2 on 2023-06-23 19:45

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_id', models.CharField(editable=False, max_length=36)),
                ('screenshot', models.ImageField(upload_to=core.models.screenshot_upload_to)),
                ('timestamp', models.PositiveIntegerField(default=0)),
                ('video', models.ManyToManyField(to='core.videos')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.TextField()),
                ('video', models.ManyToManyField(to='core.videos')),
            ],
        ),
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(editable=False, max_length=36)),
                ('audio_file', models.FileField(upload_to=core.models.audio_upload_to)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.videos')),
            ],
        ),
    ]
