# Generated by Django 4.2.2 on 2023-06-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_screenshots_paragraphs_audios'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='len_article',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
