# Generated by Django 4.2.2 on 2023-06-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paragraphs_len_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshots',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
