# Generated by Django 4.2.2 on 2023-06-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_screenshots_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshots',
            name='red_square',
            field=models.BooleanField(default=False),
        ),
    ]
