# Generated by Django 4.2.2 on 2023-07-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_screenshots_red_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraphs',
            name='timestamp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
